CREATE TABLE MEMBER
(
    `USER_ID`    VARCHAR(200)    NOT NULL    COMMENT 'USER_ID',
    `PASSWORD`   VARCHAR(200)    NOT NULL    COMMENT 'PASSWORD',
    `USER_NAME`  VARCHAR(200)    NULL        COMMENT 'USER_NAME',
    `IMG_CTT`    BLOB            NULL        COMMENT 'IMG_CTT',
    PRIMARY KEY (USER_ID)
);

-- 테이블 Comment 설정 SQL - MEMBER
ALTER TABLE MEMBER COMMENT 'MEMBER';

-- 테이블 생성 SQL - BANG
CREATE TABLE BANG
(
    `ROOM_ID`    INT             NOT NULL    COMMENT 'ROOM_ID',
    `ROOM_NAME`  VARCHAR(500)    NOT NULL    COMMENT 'ROOM_NAME',
    `IMG_CTT`    BLOB            NULL        COMMENT 'IMG_CTT',
    `ROOM_TYCD`  VARCHAR(1)      NULL        COMMENT 'ROOM_TYCD',
    PRIMARY KEY (ROOM_ID)
);

-- 테이블 Comment 설정 SQL - BANG
ALTER TABLE BANG COMMENT 'BANG';


-- 테이블 생성 SQL - BANG_JOIN
CREATE TABLE BANG_JOIN
(
    `USER_ID`  VARCHAR(200)    NOT NULL    COMMENT 'USER_ID',
    `ROOM_ID`  INT             NOT NULL    COMMENT 'ROOM_ID',
);

-- 테이블 Comment 설정 SQL - BANG_JOIN
ALTER TABLE BANG_JOIN COMMENT 'BANG_JOIN';

-- 테이블 생성 SQL - MESSAGE
CREATE TABLE MESSAGE
(
    `ID`       INTEGER          NOT NULL    AUTO_INCREMENT COMMENT 'ID',
    `ROOM_ID`  INT              NOT NULL    COMMENT 'ROOM_ID',
    `SND_ID`   VARCHAR(200)     NOT NULL    COMMENT 'SND_ID',
    `MESSAGE`  VARCHAR(4000)    NOT NULL    COMMENT 'MESSAGE',
    `SND_DTM`  DATETIME         NOT NULL    COMMENT 'SND_DTM',
    `TYPE`     VARCHAR(10)      NOT NULL    COMMENT 'TYPE',
    PRIMARY KEY (ID)
);

-- 테이블 Comment 설정 SQL - MESSAGE
ALTER TABLE MESSAGE COMMENT 'MESSAGE';

-- 테이블 생성 SQL - MEMBER_FRIEND
CREATE TABLE MEMBER_FRIEND
(
    `USER_ID`    VARCHAR(200)    NOT NULL    COMMENT 'USER_ID',
    `FRIEND_ID`  VARCHAR(200)    NOT NULL    COMMENT 'FRIEND_ID',
    PRIMARY KEY (USER_ID,FRIEND_ID)
);

-- 테이블 Comment 설정 SQL - MEMBER_FRIEND
ALTER TABLE MEMBER_FRIEND COMMENT 'MEMBER_FRIEND';